// ==UserScript==
// @name        On Screen Console
// @name:ja     画面上のコンソール
// @description Display the contents of the browser's developer tools console on the screen
// @match       *://*/*
// @author      hidao80
// @version     1.3.5
// @namespace   https://github.com/hidao80/UserScript/OnScreenConsole
// @license     MIT
// @icon        https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f5a5.png
// @run-at      document-end
// @grant       none
// @updateURL   https://github.com/hidao80/UserScript/raw/main/src/Others/OnScreenConsole/OnScreenConsole.user.js
// @downloadURL https://github.com/hidao80/UserScript/raw/main/src/Others/OnScreenConsole/OnScreenConsole.min.user.js
// ==/UserScript==
const styles=[`\n    #debug-details {\n        display: none;\n        position: absolute;\n        top: 0;\n        width: 350px;\n        opacity: 0.6;\n        z-index: 2000;\n        background-color: gray;\n        color: white;\n    }\n    `,`\n    #debug-details[open] {\n        height: -webkit-fill-available;\n        max-height: -webkit-fill-available;\n    }\n    `,`\n    #debug-div {\n        height: calc(100% - 1.2rem);\n        background-color: gray;\n        color: white;\n        overflow: scroll;\n    }\n    `,`\n    #debug-opposite {\n        cursor: pointer;\n        color: blue;\n        font-weight: 800;\n    }\n    `,`\n    .debug-top {\n        border-top: 1px solid #999;\n    }\n`];const usableSheet=[...document.styleSheets].slice(-1)[0];for(let e of styles){usableSheet.insertRule(e,usableSheet.cssRules.length)}class Multilingualization{static dictionaries={en:{"Details: ":"Details: ","Move to the Opposite":"Move to the Opposite"},ja:{"Details: ":"詳細: ","Move to the Opposite":"反対側へ移動"},es:{"Details: ":"Detalles: ","Move to the Opposite":"Pasar al otro lado"},ru:{"Details: ":"Подробности: ","Move to the Opposite":"Перейдите на другую сторону"},fr:{"Details: ":"Détails : ","Move to the Opposite":"Passez à l'opposé"},de:{"Details: ":"Détails : ","Move to the Opposite":"Auf die Gegenseite gehen"},zh:{"Details: ":"细节。","Move to the Opposite":"转移到对立面"}};static language(){const e=(window.navigator.languages&&window.navigator.languages[0]||window.navigator.language||window.navigator.userLanguage||window.navigator.browserLanguage).slice(0,2);return this.dictionaries[e]?e:"en"}static translate(e){return this.dictionaries[this.language()][e]}static translateAll(){const e=this.dictionaries[this.language()];for(let t of document.querySelectorAll("[data-translate]")){t.innerHTML=e[t.dataset.translate]}}}const div=document.createElement("div");const details=document.createElement("details");const log=e=>{const t=typeof e=="string"?`<pre>${e}<pre>`:JSON.stringify(e,undefined,1);div.insertAdjacentHTML("beforeend",`<p class="debug-top">${t}</p>`);div.scrollTop=div.scrollHeight};const alignRight=e=>{if(e){details.style.right=0;details.style.left=null}else{details.style.right=null;details.style.left=0}};const summary=document.createElement("summary");summary.textContent=Multilingualization.translate("Details: ");const moveOpposite=document.createElement("a");moveOpposite.insertAdjacentHTML("beforeend",Multilingualization.translate("Move to the Opposite"));moveOpposite.addEventListener("click",(()=>{alignRight(details.style.left=="0px")}));summary.appendChild(moveOpposite);div.setAttribute("id","debug-div");details.setAttribute("id","debug-details");moveOpposite.setAttribute("id","debug-opposite");details.appendChild(summary);details.appendChild(div);details.style.display="block";details.style.position="absolute";details.style.left=0;details.style.top=0;console.log=log;setTimeout((()=>{document.body.appendChild(details)}),300);
